// Generated by LiveScript 1.3.1
(function(){
  var request, through, gulpUtil, SWIFFY_URL;
  request = require('request');
  through = require('through2');
  gulpUtil = require('gulp-util');
  SWIFFY_URL = 'https://www.google.com/doubleclick/studio/swiffy/upload';
  function convert(file, fmt, cb){
    var r, this$ = this;
    r = request.post(SWIFFY_URL, function(err, res, body){
      var data, url;
      if (err) {
        return cb(err);
      }
      if (res.statusCode !== 200) {
        return cb(res.statusMessage);
      }
      data = JSON.parse(body.substr(4));
      data = data[data.length - 3];
      url = data[data.length - 1] + data[data.length - 2];
      return request(url, function(err, res, body){
        if (err) {
          return cb(err);
        }
        if (fmt === 'json') {
          body = (/swiffyobject\s*=\s*(.*)(?=;\s*<\/script>)/.exec(body))[1] + '\n';
        }
        file.contents = new Buffer(body);
        file.path = gulpUtil.replaceExtension(file.path, ".swf." + fmt);
        return cb(null, file);
      });
    });
    return r.form().append('swfFile', file.contents, (function(){
      switch (false) {
      case !file.isBuffer():
        return {
          filename: file.path
        };
      case !file.isStream():
        return null;
      }
    }()));
  }
  module.exports = function(fmt){
    if (fmt != null) {
      fmt = fmt.toLowerCase();
    }
    if (fmt !== 'json') {
      fmt = 'html';
    }
    return through.obj(function(file, enc, cb){
      if (file.isNull()) {
        return cb(null, file);
      }
      return convert(file, fmt, cb);
    });
  };
}).call(this);
