// Generated by LiveScript 1.3.1
(function(){
  var debug, swiffyConvert, through, join$ = [].join;
  debug = require('debug');
  swiffyConvert = require('swiffy-convert');
  through = require('through2-concurrent');
  debug = debug('swiffy');
  module.exports = function(fmt, opts){
    opts == null && (opts = {
      maxConcurrency: 10
    });
    if (fmt != null) {
      fmt = fmt.toLowerCase();
    }
    if (fmt !== 'json') {
      fmt = 'html';
    }
    return through.obj({
      maxConcurrency: opts.maxConcurrency
    }, function(file, enc, cb){
      var this$ = this;
      debug("Converting " + file.relative + ":");
      if (file.isNull()) {
        return cb(null, file);
      }
      return swiffyConvert(file.contents, function(err, res){
        var ref$;
        if (err) {
          return cb(err);
        }
        if (res.messages != null) {
          debug(("Messages for " + file.relative + ":\n") + join$.call(res.messages.map(function(it){
            return "[ " + it.type + " ] " + it.description;
          }), '\n'));
        }
        ((ref$ = file.data) != null
          ? ref$
          : file.data = {}).swiffy = {
          messages: res.messages
        };
        file.contents = new Buffer(res.output[fmt]);
        file.path = file.path.replace(/\.swf$/i, ".swf." + fmt);
        return cb(null, file);
      });
    });
  };
}).call(this);
